### ISSUE TITLE
Pose Estimation

### ISSUE THREAD

**Issue by m0ose** [muneebaadil/how-to-sfm#4]
This is a cool tutorial.

Can you explain the pose estimation part?  Where did those K values come from in section 2.5?
______
### 2.5. Pose Estimation
```
K = np.array([[2759.48,0,1520.69],[0,2764.16,1006.81],[0,0,1]])
E = K.T.dot(F.dot(K))
```

**Comment by chenkang455** [comment]
It comes from the camera calibration process.
